name: Read Hello File

on:
  push:
    branches:
      - main

jobs:
  print-hello:
    runs-on: assign-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print hello.txt contents
        run: |
          echo "📄 Contents of hello.txt:"
          cat hello.txt
