name: Read Hello File

on:
  push:
    branches:
      - main

jobs:
  read-and-print:
    runs-on: assign-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read and print hello file content
        run: |
          echo "Contents of hello.txt:"
          cat hello.txt
